"""empty message

Revision ID: bad0bf9a442b
Revises: 96edfd406177
Create Date: 2024-07-29 14:18:15.184620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bad0bf9a442b'
down_revision: Union[str, None] = '96edfd406177'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_timetable_id', table_name='timetable')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_timetable_id', 'timetable', ['id'], unique=False)
    # ### end Alembic commands ###
